{
    "vintage": {
        "id": 152489996,
        "seo_name": "chateau-valentin-blaye-cotes-de-bordeaux-2017",
        "name": "Château Valentin Blaye - Côtes de Bordeaux 2017",
        "statistics": {
            "status": "BelowThreshold",
            "ratings_count": 6,
            "ratings_average": 0,
            "labels_count": 202,
            "wine_ratings_count": 411,
            "wine_ratings_average": 3.6,
            "wine_status": "Normal",
        },
        "image": {
            "location": "//images.vivino.com/thumbs/laFzTwvOSgi9PCcDHJZhWw_pl_480x640.png",
            "variations": {
                "bottle_large": "//images.vivino.com/thumbs/laFzTwvOSgi9PCcDHJZhWw_pb_x960.png",
                "bottle_medium": "//images.vivino.com/thumbs/laFzTwvOSgi9PCcDHJZhWw_pb_x600.png",
                "bottle_medium_square": "//images.vivino.com/thumbs/laFzTwvOSgi9PCcDHJZhWw_pb_600x600.png",
                "bottle_small": "//images.vivino.com/thumbs/laFzTwvOSgi9PCcDHJZhWw_pb_x300.png",
                "bottle_small_square": "//images.vivino.com/thumbs/laFzTwvOSgi9PCcDHJZhWw_pb_300x300.png",
                "label": "//images.vivino.com/thumbs/laFzTwvOSgi9PCcDHJZhWw_pl_480x640.png",
                "label_large": "//images.vivino.com/thumbs/laFzTwvOSgi9PCcDHJZhWw_pl_375x500.png",
                "label_medium": "//images.vivino.com/thumbs/laFzTwvOSgi9PCcDHJZhWw_pl_150x200.png",
                "label_medium_square": "//images.vivino.com/thumbs/laFzTwvOSgi9PCcDHJZhWw_pl_150x150.png",
                "label_small_square": "//images.vivino.com/thumbs/laFzTwvOSgi9PCcDHJZhWw_pl_80x80.png",
                "large": "//images.vivino.com/thumbs/laFzTwvOSgi9PCcDHJZhWw_pl_375x500.png",
                "medium": "//images.vivino.com/thumbs/laFzTwvOSgi9PCcDHJZhWw_pl_150x200.png",
                "medium_square": "//images.vivino.com/thumbs/laFzTwvOSgi9PCcDHJZhWw_pl_150x150.png",
                "small_square": "//images.vivino.com/thumbs/laFzTwvOSgi9PCcDHJZhWw_pl_80x80.png",
            },
        },
        "wine": {
            "id": 1133822,
            "name": "Blaye - Côtes de Bordeaux",
            "seo_name": "blaye-cotes-de-bordeaux",
            "type_id": 1,
            "vintage_type": 0,
            "is_natural": False,
            "region": {
                "id": 3254,
                "name": "Blaye - Côtes de Bordeaux",
                "name_en": "Côtes de Blaye",
                "seo_name": "blaye-cotes-de-bordeaux",
                "country": {
                    "code": "fr",
                    "name": "Frankrijk",
                    "native_name": "France",
                    "seo_name": "france",
                    "currency": {
                        "code": "EUR",
                        "name": "Euros",
                        "prefix": "€",
                        "suffix": None,
                    },
                    "regions_count": 1306,
                    "users_count": 5982302,
                    "wines_count": 422702,
                    "wineries_count": 67544,
                    "most_used_grapes": [
                        {
                            "id": 14,
                            "name": "Pinot Noir",
                            "seo_name": "pinot-noir",
                            "has_detailed_info": True,
                            "wines_count": 572334,
                            "parent_grape_id": None,
                        },
                        {
                            "id": 5,
                            "name": "Chardonnay",
                            "seo_name": "chardonnay",
                            "has_detailed_info": True,
                            "wines_count": 604208,
                            "parent_grape_id": None,
                        },
                        {
                            "id": 10,
                            "name": "Merlot",
                            "seo_name": "merlot",
                            "has_detailed_info": True,
                            "wines_count": 566719,
                            "parent_grape_id": None,
                        },
                    ],
                },
                "class": {"typecast_map": {"background_image": {}, "class": {}}},
                "background_image": None,
            },
            "winery": {
                "id": 242308,
                "name": "Château Valentin",
                "seo_name": "chateau-valentin",
                "status": 0,
                "background_image": None,
            },
            "taste": {
                "structure": {
                    "acidity": 3.7399254,
                    "fizziness": None,
                    "intensity": 3.992119,
                    "sweetness": 1.1157621,
                    "tannin": 3.3033457,
                    "user_structure_count": 12,
                    "calculated_structure_count": 16,
                },
                "flavor": [
                    {
                        "group": "spices",
                        "stats": {"count": 5, "score": 600},
                        "primary_keywords": [
                            {"id": 320, "name": "peper", "count": 4},
                            {"id": 249, "name": "drop", "count": 2},
                        ],
                    },
                    {
                        "group": "microbio",
                        "stats": {"count": 2, "score": 200},
                        "primary_keywords": [{"id": 91, "name": "kaas", "count": 2}],
                    },
                    {
                        "group": "oak",
                        "stats": {"count": 2, "score": 200},
                        "primary_keywords": [{"id": 292, "name": "eiken", "count": 2}],
                    },
                    {
                        "group": "black_fruit",
                        "stats": {"count": 1, "score": 100},
                        "primary_keywords": [
                            {"id": 135, "name": "donker fruit", "count": 1}
                        ],
                    },
                    {
                        "group": "red_fruit",
                        "stats": {"count": 1, "score": 100},
                        "primary_keywords": [{"id": 93, "name": "kers", "count": 1}],
                    },
                    {
                        "group": "vegetal",
                        "stats": {"count": 1, "score": 100},
                        "primary_keywords": [
                            {"id": 426, "name": "tomatenblad", "count": 1}
                        ],
                    },
                ],
            },
            "statistics": {
                "status": "Normal",
                "ratings_count": 411,
                "ratings_average": 3.6,
                "labels_count": 4874,
                "vintages_count": 38,
            },
            "style": {
                "id": 19,
                "seo_name": "bordeaux-red",
                "regional_name": "Bordeaux",
                "varietal_name": "Rood",
                "name": "Bordeaux Rood",
                "image": None,
                "background_image": None,
                "description": "Bordeaux has a cool marine coastal climate, with mild weather and no dry season. Bordeaux reds tend to be lower in alcohol and are slightly lighter in body.\n\nStylistically, they exhibit more nuanced flavors and less up-front fruit. Sophisticated and elegant, they pair well with game meats, roast lamb, or hearty beef stews.\n\nBordeaux is the largest wine producing region in France. It consists of two major areas—the Left and the Right Bank. Both lie in the heart of the Gironde estuary and are further divided by its tributaries, the Garonne and the Dordogne rivers.\n\nWhile the Right Bank produces blends that are mostly Merlot dominant, the Left Bank produces blends that are primarily Cabernet Sauvignon dominant.\n\nBordeaux reds are said to be terroir-driven (if you like French wines, you'll hear this term a lot). Terroir is a concise way to define a specific region based upon the soil, climate, and the collective knowledge of the generations of people who have farmed the land.\n\nWhen shopping for Bordeaux reds, keep in mind, French wines are all about the region and the blend, not about individual grape varieties. In fact, you will rarely find blend percentages listed on the label.\n\nCollectively, Bordeaux produces 700 million bottles of wine in an average year! While some of the most expensive wines in the world come from Bordeaux, most are every day, affordable table wines.",
                "blurb": None,
                "interesting_facts": [
                    "The Brits call red Bordeaux blends “claret.”",
                    "Château is a common term for a French wine producer.",
                    "Both dry and sweet whites can be found in Bordeaux, typically they are made from Sauvignon Blanc, Sémillon and sometimes Muscadelle.",
                    "Bordeaux has been a wine producing region for a very long time: The first vines were planted in the region during the mid-1st century by the Romans.",
                    "Phylloxera wiped out most of Bordeaux's vineyards in the late 19th century. Vineyards were gradually replanted with Phylloxera resistant root stock.",
                ],
                "body": 4,
                "body_description": "Zeer full-bodied",
                "acidity": 3,
                "acidity_description": "Hoog",
                "country": {
                    "code": "fr",
                    "name": "Frankrijk",
                    "native_name": "France",
                    "seo_name": "france",
                    "currency": {
                        "code": "EUR",
                        "name": "Euros",
                        "prefix": "€",
                        "suffix": None,
                    },
                    "regions_count": 1306,
                    "users_count": 5982302,
                    "wines_count": 422702,
                    "wineries_count": 67544,
                    "most_used_grapes": [
                        {
                            "id": 14,
                            "name": "Pinot Noir",
                            "seo_name": "pinot-noir",
                            "has_detailed_info": True,
                            "wines_count": 572334,
                            "parent_grape_id": None,
                        },
                        {
                            "id": 5,
                            "name": "Chardonnay",
                            "seo_name": "chardonnay",
                            "has_detailed_info": True,
                            "wines_count": 604208,
                            "parent_grape_id": None,
                        },
                        {
                            "id": 10,
                            "name": "Merlot",
                            "seo_name": "merlot",
                            "has_detailed_info": True,
                            "wines_count": 566719,
                            "parent_grape_id": None,
                        },
                    ],
                },
                "wine_type_id": 1,
                "food": [
                    {
                        "id": 4,
                        "name": "Rundvlees",
                        "background_image": {
                            "location": "//images.vivino.com/backgrounds/foods/4_beef.png",
                            "variations": {
                                "small": "//images.vivino.com/backgrounds/foods/thumbs/4_beef_932x810.png"
                            },
                        },
                        "seo_name": "beef",
                    },
                    {
                        "id": 9,
                        "name": "Kalfsvlees",
                        "background_image": {
                            "location": "//images.vivino.com/backgrounds/foods/9_veal.png",
                            "variations": {
                                "small": "//images.vivino.com/backgrounds/foods/thumbs/9_veal_932x810.png"
                            },
                        },
                        "seo_name": "veal",
                    },
                    {
                        "id": 11,
                        "name": "Wild (hert)",
                        "background_image": {
                            "location": "//images.vivino.com/backgrounds/foods/11_venison.png",
                            "variations": {
                                "small": "//images.vivino.com/backgrounds/foods/thumbs/11_venison_932x810.png"
                            },
                        },
                        "seo_name": "game",
                    },
                    {
                        "id": 20,
                        "name": "Gevogelte",
                        "background_image": {
                            "location": "//images.vivino.com/backgrounds/foods/20_chicken.png",
                            "variations": {
                                "small": "//images.vivino.com/backgrounds/foods/thumbs/20_chicken_932x810.png"
                            },
                        },
                        "seo_name": "poultry",
                    },
                ],
                "grapes": [
                    {
                        "id": 2,
                        "name": "cabernet sauvignon",
                        "seo_name": "cabernet-sauvignon",
                        "has_detailed_info": True,
                        "wines_count": 801751,
                        "parent_grape_id": None,
                    },
                    {
                        "id": 3,
                        "name": "Cabernet franc",
                        "seo_name": "cabernet-franc",
                        "has_detailed_info": True,
                        "wines_count": 269578,
                        "parent_grape_id": None,
                    },
                    {
                        "id": 9,
                        "name": "Malbec",
                        "seo_name": "malbec",
                        "has_detailed_info": True,
                        "wines_count": 219735,
                        "parent_grape_id": None,
                    },
                    {
                        "id": 10,
                        "name": "Merlot",
                        "seo_name": "merlot",
                        "has_detailed_info": True,
                        "wines_count": 566719,
                        "parent_grape_id": None,
                    },
                    {
                        "id": 42,
                        "name": "Petit verdot",
                        "seo_name": "petit-verdot",
                        "has_detailed_info": True,
                        "wines_count": 82567,
                        "parent_grape_id": None,
                    },
                    {
                        "id": 51,
                        "name": "Carménère",
                        "seo_name": "carmenere",
                        "has_detailed_info": True,
                        "wines_count": 50087,
                        "parent_grape_id": None,
                    },
                ],
                "region": {
                    "id": 383,
                    "name": "Bordeaux",
                    "name_en": "",
                    "seo_name": "bordeaux",
                    "country": {
                        "code": "fr",
                        "name": "Frankrijk",
                        "native_name": "France",
                        "seo_name": "france",
                        "currency": {
                            "code": "EUR",
                            "name": "Euros",
                            "prefix": "€",
                            "suffix": None,
                        },
                        "regions_count": 1306,
                        "users_count": 5982302,
                        "wines_count": 422702,
                        "wineries_count": 67544,
                        "most_used_grapes": [
                            {
                                "id": 14,
                                "name": "Pinot Noir",
                                "seo_name": "pinot-noir",
                                "has_detailed_info": True,
                                "wines_count": 572334,
                                "parent_grape_id": None,
                            },
                            {
                                "id": 5,
                                "name": "Chardonnay",
                                "seo_name": "chardonnay",
                                "has_detailed_info": True,
                                "wines_count": 604208,
                                "parent_grape_id": None,
                            },
                            {
                                "id": 10,
                                "name": "Merlot",
                                "seo_name": "merlot",
                                "has_detailed_info": True,
                                "wines_count": 566719,
                                "parent_grape_id": None,
                            },
                        ],
                    },
                    "parent_id": None,
                    "background_image": {
                        "location": "//images.vivino.com/regions/backgrounds/3z0tiBnOSPaSk5LxoYKRYg.jpeg",
                        "variations": {
                            "large": "//thumbs.vivino.com/region_backgrounds/3z0tiBnOSPaSk5LxoYKRYg_1280x760.jpeg",
                            "medium": "//thumbs.vivino.com/region_backgrounds/3z0tiBnOSPaSk5LxoYKRYg_600x356.jpeg",
                        },
                    },
                    "class": {"typecast_map": {"background_image": {}, "class": {}}},
                    "statistics": {
                        "wineries_count": 13204,
                        "wines_count": 41989,
                        "sub_regions_count": 12,
                        "parent_regions_count": 0,
                    },
                },
                "parent_style_id": 779,
                "hidden": False,
                "statistics": {"wines_count": 32085, "aggregated_wines_count": 52068},
                "vintage_mask": "1<",
                "baseline_structure": {
                    "acidity": 4.0,
                    "fizziness": None,
                    "intensity": 4.0,
                    "sweetness": 1.0,
                    "tannin": 4.0,
                },
            },
            "has_valid_ratings": True,
        },
        "year": 2017,
        "grapes": None,
        "has_valid_ratings": False,
    },
    "price": {
        "id": 30598233,
        "amount": 5.7,
        "discounted_from": None,
        "discount_percent": None,
        "type": "vc",
        "sku": "46322",
        "url": "https://vinotheque-bordeaux.com/bordeaux/5390-76519-chateau-valentin.html#/6-format-bouteille_075_l",
        "visibility": 1,
        "bottle_type_id": 1,
        "currency": {"code": "EUR", "name": "Euros", "prefix": "€", "suffix": None},
        "bottle_type": {
            "id": 1,
            "name": "Fles (0.75 l)",
            "short_name": "fles",
            "short_name_plural": "fles",
            "volume_ml": 750,
        },
    },
    "prices": [
        {
            "id": 30598233,
            "amount": 5.7,
            "discounted_from": None,
            "discount_percent": None,
            "type": "vc",
            "sku": "46322",
            "url": "https://vinotheque-bordeaux.com/bordeaux/5390-76519-chateau-valentin.html#/6-format-bouteille_075_l",
            "visibility": 1,
            "bottle_type_id": 1,
            "currency": {"code": "EUR", "name": "Euros", "prefix": "€", "suffix": None},
            "bottle_type": {
                "id": 1,
                "name": "Fles (0.75 l)",
                "short_name": "fles",
                "short_name_plural": "fles",
                "volume_ml": 750,
            },
        }
    ],
}
